POST http://localhost:3000/songs.json
Content-Type: application/json

{
  "title": "Gnossiennes: No. 1, Lent",
  "album": "Satie: Works for Piano",
  "artist": "Erik Satie, Marcel Worms", 
  "year": 2016
}

###

DELETE http://localhost:3000/songs/3.json

###

PATCH http://localhost:3000/songs/4.json
Content-Type: application/json

{
  "title": "Marigold",
  "album": "Bloom",
  "artist": "Caligula's Horse", 
  "year": 2015
}